### ISSUE TITLE
Random Encounter issue

### ISSUE THREAD

**Issue by Deeren1** [LecodeMV/leTBS#12]
I'm having a problem using the random encounter plug in. It works fine when I start a new game. I play through the game until I get to the map I have the encounters on, and it works just fine. If I save the game before going onto the map, go to the title screen, and continue the save file, it still works fine. However, if I close the game entirely, open the game back up and load the save, there's never a single encounter even after a minute of walking around the map. I tried looking at the demo to see if there was a clue as to what I was doing wrong, but the demo doesn't have the random encounter functionality on its maps. Minus the plugins I've installed myself, everything is set up exactly like the demo.
![mine1](https://user-images.githubusercontent.com/50462315/57482033-6e9d4580-7258-11e9-873c-724535af5878.PNG)
![mine2](https://user-images.githubusercontent.com/50462315/57482048-7bba3480-7258-11e9-836d-ea5ee56e2b84.PNG)
![map](https://user-images.githubusercontent.com/50462315/57482184-d6ec2700-7258-11e9-8b43-697644da5e78.PNG)
Attached is my plugin list, as well as the map in question. I don't know a thing about javascript coding, otherwise I would deep dive the js files. Let me know if you need any other information. Thanks!

**Comment by LecodeMV** [comment]
Hello. I'm keeping note on your issue. I can't really help you however. I'll make sure it'll work in the next version.
