### ISSUE TITLE
Good for you

### ISSUE THREAD

**Issue by ChillMagic** [LecodeMV/leTBS#3]
I'm now making a SRPG System (TBS) on RMVA too.
I heard that there is a TBS-System Maker.
It is very good.

I have an idea.
The 'range' in map (AOE) from your project, is like this:
```
"[cx,cy-1],[cx-1,cy],[cx,cy],[cx+1,cy],[cx,cy+1]"
```
The same thing with me, is like this:
```
MAP (
010
1P1
010
)
```
I think your structure is figured out by 'eval', it is very convenient for parsing.
But I think there is a little difficult for users to modify.
And, if an AOE Structure is consist of different values, like this:
```
MAP (
00100
01210
12P21
01210
00100
)
```
'1' is expressed as 'level 1', '2' is expressed as 'level 2', 'P' is the position of attacker.
The detailed parameters about 'level 1' 'level 2' will be set in other place.

Of course, these are just my little advice.

Good luck!

**Comment by fabio-dev** [comment]
A very nice idea, it would be easier to configure and it would open up possibilities for future customizations
+1

**Comment by LecodeMV** [comment]
The point of the AoE creator is to avoid touching at any code or script-like thing to configure an AoE.
So I don't see why users would want to modify an AoE by the code itself, and not using the tool.

**Comment by ChillMagic** [comment]
@LecodeMV  I mean that, users use AOE creator, but the creator generates the different code. It is easy for parsing and reading, so that users can modifiy it too.
