### ISSUE TITLE
Problem with Demo

### ISSUE THREAD

**Issue by yergui** [LecodeMV/leTBS#4]
Hi, i downloaded the Demo following the documentation on the page: https://lecodemv.github.io/leTBS/ And when I give it to try it I get the error "TypeError undefined is not a function" (Attached image)

How do you fix it to work? I use RPG Maker MV 1.4

A greeting and a good job for the project
![rpg maker mv](https://cloud.githubusercontent.com/assets/26770204/24459901/f919d096-149c-11e7-9508-67b4efd0dae6.png)

**Comment by yergui** [comment]
Hi, i updated RPG Maker MV to 1.4 version, but the problem continues to appear

**Comment by LecodeMV** [comment]
Hello. My apologies for the late reply. It should be ok now, with the release of the 0.7 version.
